nav:
  - Essentials:
    - SSH access: essentials/ssh_access.md
    - Firewall: essentials/firewall.md
    - Bash: essentials/scripting.md
    - Partitioning: essentials/partitions.md
  - Networking:
    - Floating IP: networking/floating.md
    - Subnet: networking/subnet.md
    - Bond: networking/bond.md
  - Bare metal:
    - Console: baremetal/console.md
    - Server health:
      - Disk health: essentials/health_monitoring/disk.md
      - Disk health: essentials/health_monitoring/sensors.md
      - Disk health: essentials/health_monitoring/disk

  - Cherry services:
    - Backup storage: cherry-services/backupstorage.md
    - Elastic Block Storage: cherry-services/ebs.md
    - Load balancer: cherry-services/lb.md